// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: grpc_services.proto

package codeless_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelegramDesignService_CreateDesign_FullMethodName = "/codeless_grpc.TelegramDesignService/CreateDesign"
	TelegramDesignService_DeleteDesign_FullMethodName = "/codeless_grpc.TelegramDesignService/DeleteDesign"
)

// TelegramDesignServiceClient is the client API for TelegramDesignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelegramDesignServiceClient interface {
	CreateDesign(ctx context.Context, in *IdDesignRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	DeleteDesign(ctx context.Context, in *IdDesignRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type telegramDesignServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramDesignServiceClient(cc grpc.ClientConnInterface) TelegramDesignServiceClient {
	return &telegramDesignServiceClient{cc}
}

func (c *telegramDesignServiceClient) CreateDesign(ctx context.Context, in *IdDesignRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, TelegramDesignService_CreateDesign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramDesignServiceClient) DeleteDesign(ctx context.Context, in *IdDesignRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, TelegramDesignService_DeleteDesign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegramDesignServiceServer is the server API for TelegramDesignService service.
// All implementations must embed UnimplementedTelegramDesignServiceServer
// for forward compatibility.
type TelegramDesignServiceServer interface {
	CreateDesign(context.Context, *IdDesignRequest) (*ErrorResponse, error)
	DeleteDesign(context.Context, *IdDesignRequest) (*ErrorResponse, error)
	mustEmbedUnimplementedTelegramDesignServiceServer()
}

// UnimplementedTelegramDesignServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelegramDesignServiceServer struct{}

func (UnimplementedTelegramDesignServiceServer) CreateDesign(context.Context, *IdDesignRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDesign not implemented")
}
func (UnimplementedTelegramDesignServiceServer) DeleteDesign(context.Context, *IdDesignRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDesign not implemented")
}
func (UnimplementedTelegramDesignServiceServer) mustEmbedUnimplementedTelegramDesignServiceServer() {}
func (UnimplementedTelegramDesignServiceServer) testEmbeddedByValue()                               {}

// UnsafeTelegramDesignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramDesignServiceServer will
// result in compilation errors.
type UnsafeTelegramDesignServiceServer interface {
	mustEmbedUnimplementedTelegramDesignServiceServer()
}

func RegisterTelegramDesignServiceServer(s grpc.ServiceRegistrar, srv TelegramDesignServiceServer) {
	// If the following call pancis, it indicates UnimplementedTelegramDesignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelegramDesignService_ServiceDesc, srv)
}

func _TelegramDesignService_CreateDesign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdDesignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramDesignServiceServer).CreateDesign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramDesignService_CreateDesign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramDesignServiceServer).CreateDesign(ctx, req.(*IdDesignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramDesignService_DeleteDesign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdDesignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramDesignServiceServer).DeleteDesign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramDesignService_DeleteDesign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramDesignServiceServer).DeleteDesign(ctx, req.(*IdDesignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelegramDesignService_ServiceDesc is the grpc.ServiceDesc for TelegramDesignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramDesignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codeless_grpc.TelegramDesignService",
	HandlerType: (*TelegramDesignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDesign",
			Handler:    _TelegramDesignService_CreateDesign_Handler,
		},
		{
			MethodName: "DeleteDesign",
			Handler:    _TelegramDesignService_DeleteDesign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_services.proto",
}
